# ./docker-compose.yml

version: "3.3"
services:
  frontend-container:
    image: php:8.0-apache
    container_name: frontend
    depends_on:
      - backend-container
    volumes: 
      - ./frontend:/var/www/html/
    ports:
      - "8000:80"

  database-container:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker-user"
      MYSQL_PASSWORD: "docker-psw"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "6032:3306"

  backend-container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - database-container
    volumes:
      - ./backend:/var/www/html/
    ports:
      - "8001:80"
